# Limpieza y Completado de datos relevantes
## Proyecto Final

**Equipo:**
* Malváez Flores Axel Daniel
* Peralta Rionda Gabriel Zadquiel

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
# Cargamos los dos data sets

staff = pd.read_csv('./TablasCleaned/baStaff_cleaned.csv')
stock = pd.read_csv('./TablasCleaned/baStock_cleaned.csv')
invoices = pd.read_csv('./TablasCleaned/baInvoices_cleaned.csv')
invoicesItems = pd.read_csv('./TablasCleaned/baInvoicesItems_cleaned.csv')

## InvoicesItems

In [30]:
invoicesItems

InvoiceItemID  InvoiceID  StockID  \
0                  1          1        5   
1                  2          2       78   
2                  3          2       66   
3                  4          3     2568   
4                  5          4      732   
...              ...        ...      ...   
50308          50310      28750      228   
50309          50311      28751       62   
50310          50312      28752     2490   
50311          50313      28753      826   
50312          50314      28754     2642   

                                   Description  Price Unit  Total_sin_iva  \
0               de la rosa bianchi grande 45pz      29.000          24.36   
1                 reyma 7oz vaso plastico 50pz      30.000          25.20   
2                classy cuchara pastelera 50pz      13.000          10.92   
3                             macma deju 280gr      61.000          51.24   
4                          macma escoces 330gr      57.000          47.88   
...                                        ...         ...            ...   
50308             12x25 celofan adhesivo 100pz      43.000          36.12   
50309          25x35 pb hoja mediana polipapel       0.069          57.96   
50310                ricolino kranky mini 25pz      67.000          56.28   
50311            macma selecciones chico 330gr      65.000          54.60   
50312  meltblown cubrebocas tricapa 50pz negro      50.000          42.00   

         IVA  Total  CostPrice  Ganancia  LineNbr  
0       4.64   29.0   22.50000   6.50000        1  
1       4.80   30.0   23.40000   6.60000        1  
2       2.08   13.0    8.83000   4.17000        2  
3       9.76   61.0   48.60000  12.40000        1  
4       9.12   57.0   45.49000  11.51000        1  
...      ...    ...        ...       ...      ...  
50308   6.88   43.0   27.00000  16.00000        1  
50309  11.04   69.0    0.05458  68.94542        1  
50310  10.72   67.0   52.90000  14.10000        1  
50311  10.40   65.0    0.00000  65.00000        1  
50312   8.00   50.0   22.50000  27.50000        1  

[50313 rows x 11 columns]

In [31]:
y = (invoicesItems['Total'] * 0.16)
x = (invoicesItems['Total'] - y)
z = (x + y)
w = z - invoicesItems['CostPrice']

invoicesItems.insert(5, 'Total_sin_iva', x)
invoicesItems.insert(6, 'IVA', y)
invoicesItems.drop('Total', axis=1, inplace=True)
invoicesItems.insert(7, 'Total', z)

invoicesItems.insert(9, 'Ganancia', w)

invoicesItems

ValueError: cannot insert Total_sin_iva, already exists

## Invoices

In [ ]:
invoices

InvoiceID  InvoiceNumber        Date Creation         Date Invoice  \
0              1              1  2022-01-11 10:15:06  2022-01-11 00:00:00   
1              2              2  2022-01-11 10:29:02  2022-01-11 00:00:00   
2              3              3  2022-01-10 10:43:53  2022-01-10 00:00:00   
3              4              4  2022-01-10 10:44:34  2022-01-10 00:00:00   
4              5              5  2022-01-10 10:44:57  2022-01-10 00:00:00   
...          ...            ...                  ...                  ...   
28749      28750          28740  2022-12-19 18:52:34  2022-12-19 00:00:00   
28750      28751          28741  2022-12-19 18:57:23  2022-12-19 00:00:00   
28751      28752          28742  2022-12-19 18:56:35  2022-12-19 00:00:00   
28752      28753          28743  2022-12-19 18:59:11  2022-12-19 00:00:00   
28753      28754          28744  2022-12-19 19:05:31  2022-12-19 00:00:00   

       Sub Total  Total                           Total letter  StaffID  \
0           29.0   29.0        (VEINTINUEVE PESOS 00/100 M.N.)        3   
1           43.0   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        3   
2           61.0   61.0       (SESENTA Y UN PESOS 00/100 M.N.)        3   
3           57.0   57.0  (CINCUENTA Y SIETE PESOS 00/100 M.N.)        3   
4           43.0   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        3   
...          ...    ...                                    ...      ...   
28749       43.0   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        2   
28750       69.0   69.0    (SESENTA Y NUEVE PESOS 00/100 M.N.)        3   
28751       67.0   67.0    (SESENTA Y SIETE PESOS 00/100 M.N.)        2   
28752       65.0   65.0    (SESENTA Y CINCO PESOS 00/100 M.N.)        2   
28753       50.0   50.0          (CINCUENTA PESOS 00/100 M.N.)        6   

       Barcode  
0      3000019  
1      3000028  
2      3000037  
3      3000046  
4      3000055  
...        ...  
28749  3287505  
28750  3287514  
28751  3287523  
28752  3287532  
28753  3287541  

[28754 rows x 9 columns]

In [ ]:
invoices['StaffID'].unique()

array([3, 2, 6, 1])

In [ ]:
six = invoices[invoices['StaffID'] == 6]['StaffID'].index
for i in six:
    invoices.loc[i, 'StaffID'] = 4
invoices['StaffID'].unique()

array([3, 2, 4, 1])

In [ ]:
invoices

InvoiceID  InvoiceNumber        Date Creation         Date Invoice  \
0              1              1  2022-01-11 10:15:06  2022-01-11 00:00:00   
1              2              2  2022-01-11 10:29:02  2022-01-11 00:00:00   
2              3              3  2022-01-10 10:43:53  2022-01-10 00:00:00   
3              4              4  2022-01-10 10:44:34  2022-01-10 00:00:00   
4              5              5  2022-01-10 10:44:57  2022-01-10 00:00:00   
...          ...            ...                  ...                  ...   
28749      28750          28740  2022-12-19 18:52:34  2022-12-19 00:00:00   
28750      28751          28741  2022-12-19 18:57:23  2022-12-19 00:00:00   
28751      28752          28742  2022-12-19 18:56:35  2022-12-19 00:00:00   
28752      28753          28743  2022-12-19 18:59:11  2022-12-19 00:00:00   
28753      28754          28744  2022-12-19 19:05:31  2022-12-19 00:00:00   

       Sub Total  Total                           Total letter  StaffID  \
0           29.0   29.0        (VEINTINUEVE PESOS 00/100 M.N.)        3   
1           43.0   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        3   
2           61.0   61.0       (SESENTA Y UN PESOS 00/100 M.N.)        3   
3           57.0   57.0  (CINCUENTA Y SIETE PESOS 00/100 M.N.)        3   
4           43.0   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        3   
...          ...    ...                                    ...      ...   
28749       43.0   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        2   
28750       69.0   69.0    (SESENTA Y NUEVE PESOS 00/100 M.N.)        3   
28751       67.0   67.0    (SESENTA Y SIETE PESOS 00/100 M.N.)        2   
28752       65.0   65.0    (SESENTA Y CINCO PESOS 00/100 M.N.)        2   
28753       50.0   50.0          (CINCUENTA PESOS 00/100 M.N.)        4   

       Barcode  
0      3000019  
1      3000028  
2      3000037  
3      3000046  
4      3000055  
...        ...  
28749  3287505  
28750  3287514  
28751  3287523  
28752  3287532  
28753  3287541  

[28754 rows x 9 columns]

Se hizo revisión que todos los ID's fueran únicos, así mismo como 'Barcode'.

In [ ]:
invoices[invoices['Sub Total'] != invoices['Total']]

Empty DataFrame
Columns: [InvoiceID, InvoiceNumber, Date Creation, Date Invoice, Sub Total, Total, Total letter, StaffID, Barcode]
Index: []

Entonces como podemos observar nuestros productos no cuentan con el IVA por separado, por lo que agregaremos una columna que nos indique cuánto está siendo de IVA.

In [ ]:
y = (invoices['Sub Total'] * 0.16)
invoices['Sub Total'] = invoices['Sub Total'] - (invoices['Sub Total'] * 0.16)
invoices.insert(5, 'IVA', y)
invoices

InvoiceID  InvoiceNumber        Date Creation         Date Invoice  \
0              1              1  2022-01-11 10:15:06  2022-01-11 00:00:00   
1              2              2  2022-01-11 10:29:02  2022-01-11 00:00:00   
2              3              3  2022-01-10 10:43:53  2022-01-10 00:00:00   
3              4              4  2022-01-10 10:44:34  2022-01-10 00:00:00   
4              5              5  2022-01-10 10:44:57  2022-01-10 00:00:00   
...          ...            ...                  ...                  ...   
28749      28750          28740  2022-12-19 18:52:34  2022-12-19 00:00:00   
28750      28751          28741  2022-12-19 18:57:23  2022-12-19 00:00:00   
28751      28752          28742  2022-12-19 18:56:35  2022-12-19 00:00:00   
28752      28753          28743  2022-12-19 18:59:11  2022-12-19 00:00:00   
28753      28754          28744  2022-12-19 19:05:31  2022-12-19 00:00:00   

       Sub Total    IVA  Total                           Total letter  \
0          24.36   4.64   29.0        (VEINTINUEVE PESOS 00/100 M.N.)   
1          36.12   6.88   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)   
2          51.24   9.76   61.0       (SESENTA Y UN PESOS 00/100 M.N.)   
3          47.88   9.12   57.0  (CINCUENTA Y SIETE PESOS 00/100 M.N.)   
4          36.12   6.88   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)   
...          ...    ...    ...                                    ...   
28749      36.12   6.88   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)   
28750      57.96  11.04   69.0    (SESENTA Y NUEVE PESOS 00/100 M.N.)   
28751      56.28  10.72   67.0    (SESENTA Y SIETE PESOS 00/100 M.N.)   
28752      54.60  10.40   65.0    (SESENTA Y CINCO PESOS 00/100 M.N.)   
28753      42.00   8.00   50.0          (CINCUENTA PESOS 00/100 M.N.)   

       StaffID  Barcode  
0            3  3000019  
1            3  3000028  
2            3  3000037  
3            3  3000046  
4            3  3000055  
...        ...      ...  
28749        2  3287505  
28750        3  3287514  
28751        2  3287523  
28752        2  3287532  
28753        4  3287541  

[28754 rows x 10 columns]

Cambiamos los tipos de datos a fechas

In [ ]:
invoices['Date Creation'] = pd.to_datetime(invoices['Date Creation'])
invoices['Date Invoice'] = pd.to_datetime(invoices['Date Invoice'])
invoices

InvoiceID  InvoiceNumber       Date Creation Date Invoice  Sub Total  \
0              1              1 2022-01-11 10:15:06   2022-01-11      24.36   
1              2              2 2022-01-11 10:29:02   2022-01-11      36.12   
2              3              3 2022-01-10 10:43:53   2022-01-10      51.24   
3              4              4 2022-01-10 10:44:34   2022-01-10      47.88   
4              5              5 2022-01-10 10:44:57   2022-01-10      36.12   
...          ...            ...                 ...          ...        ...   
28749      28750          28740 2022-12-19 18:52:34   2022-12-19      36.12   
28750      28751          28741 2022-12-19 18:57:23   2022-12-19      57.96   
28751      28752          28742 2022-12-19 18:56:35   2022-12-19      56.28   
28752      28753          28743 2022-12-19 18:59:11   2022-12-19      54.60   
28753      28754          28744 2022-12-19 19:05:31   2022-12-19      42.00   

         IVA  Total                           Total letter  StaffID  Barcode  
0       4.64   29.0        (VEINTINUEVE PESOS 00/100 M.N.)        3  3000019  
1       6.88   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        3  3000028  
2       9.76   61.0       (SESENTA Y UN PESOS 00/100 M.N.)        3  3000037  
3       9.12   57.0  (CINCUENTA Y SIETE PESOS 00/100 M.N.)        3  3000046  
4       6.88   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        3  3000055  
...      ...    ...                                    ...      ...      ...  
28749   6.88   43.0    (CUARENTA Y TRES PESOS 00/100 M.N.)        2  3287505  
28750  11.04   69.0    (SESENTA Y NUEVE PESOS 00/100 M.N.)        3  3287514  
28751  10.72   67.0    (SESENTA Y SIETE PESOS 00/100 M.N.)        2  3287523  
28752  10.40   65.0    (SESENTA Y CINCO PESOS 00/100 M.N.)        2  3287532  
28753   8.00   50.0          (CINCUENTA PESOS 00/100 M.N.)        4  3287541  

[28754 rows x 10 columns]

## Staff

In [ ]:
staff

StaffID      Name  Function                                     Comments  \
0        1       UNO         4                  inventario inicial 27/07/20   
1        2  MARYCRUZ         4                                          NaN   
2        3    CARMEN         4  sandibel marin hernandez_x000d_\n21 octubre   
3        6    LORENA         4                                          NaN   

   MustBeSynchronized  VersionSync  
0                True           76  
1                True          125  
2                True          121  
3                True          120

Dado que UNO es la caja principal y es el correspondiente al dueño, procedemos a sustituir este valor por el nombre del dueño.

In [ ]:
staff.loc[0,['Name']] = 'GABRIEL'
staff = staff.drop(['MustBeSynchronized', 'VersionSync'], axis=1)
staff

StaffID      Name  Function                                     Comments
0        1      JEFE         4                  inventario inicial 27/07/20
1        2  MARYCRUZ         4                                          NaN
2        3    CARMEN         4  sandibel marin hernandez_x000d_\n21 octubre
3        6    LORENA         4                                          NaN

In [ ]:
staff.loc[3,['StaffID']] = 4
staff

StaffID      Name  Function                                     Comments
0        1      JEFE         4                  inventario inicial 27/07/20
1        2  MARYCRUZ         4                                          NaN
2        3    CARMEN         4  sandibel marin hernandez_x000d_\n21 octubre
3        4    LORENA         4                                          NaN

## Stock

In [ ]:
stock.head(3)

StockID     Familly                                          Item  \
0        1  DE LA ROSA  de la rosa bianchi choco amarillo 50pz 350gr   
1        2  DE LA ROSA   CAJA de la rosa bianchi choco amarillo c/20   
2        3  DE LA ROSA                de la rosa wafertin 24pz 528gr   

   CostPrice  QtyMinimum  BarCode  PriceList  Package  QtyPresStores  \
0       47.4           1       17       60.0    False              2   
1      948.0           0       24     1185.0     True              0   
2       51.4           1       31       65.0    False              1   

   QtyPresTotal  QtyTOTAL  QtyAvailable  QtyAvailableForStore  Level  \
0             2         2             2                     7      2   
1             0         0             0                     0      1   
2             1         1             1                     1      2   

   VersionSync  AverageSaleQty   CommentWhenAvailableForStore  
0       168663           876.0      2 disponible de inmediato  
1       171420             0.0  NO DISPONIBLE (NO PROGRAMADO)  
2       169278            89.0      1 disponible de inmediato

In [ ]:
len(stock)

3041

In [ ]:
x = stock[stock['QtyPresStores'] == stock['QtyPresTotal']]
y = x[x['QtyTOTAL'] != x['QtyAvailable']]
y[y['QtyAvailable'] != y['QtyAvailableForStore']]

Empty DataFrame
Columns: [StockID, Familly, Item, CostPrice, QtyMinimum, BarCode, PriceList, Package, QtyPresStores, QtyPresTotal, QtyTOTAL, QtyAvailable, QtyAvailableForStore, Level, VersionSync, AverageSaleQty, CommentWhenAvailableForStore]
Index: []

In [ ]:
stock.drop(['QtyPresStores', 'QtyPresTotal', 'QtyTOTAL'], axis=1, inplace=True)
stock.head(3)

StockID     Familly                                          Item  \
0        1  DE LA ROSA  de la rosa bianchi choco amarillo 50pz 350gr   
1        2  DE LA ROSA   CAJA de la rosa bianchi choco amarillo c/20   
2        3  DE LA ROSA                de la rosa wafertin 24pz 528gr   

   CostPrice  QtyMinimum  BarCode  PriceList  Package  QtyAvailable  \
0       47.4           1       17       60.0    False             2   
1      948.0           0       24     1185.0     True             0   
2       51.4           1       31       65.0    False             1   

   QtyAvailableForStore  Level  VersionSync  AverageSaleQty  \
0                     7      2       168663           876.0   
1                     0      1       171420             0.0   
2                     1      2       169278            89.0   

    CommentWhenAvailableForStore  
0      2 disponible de inmediato  
1  NO DISPONIBLE (NO PROGRAMADO)  
2      1 disponible de inmediato

In [ ]:
stock['Level'].unique()

array([2, 1])

In [ ]:
stock.drop(['Level'], axis=1, inplace=True)

In [ ]:
stock['VersionSync'].unique()

array([168663, 171420, 169278, ..., 168228, 161086, 171042])

In [ ]:
for col in stock.columns:
    print(col, len(stock[col].unique()))

StockID 3041
Familly 326
Item 3041
CostPrice 1483
QtyMinimum 22
BarCode 3041
PriceList 759
Package 2
QtyAvailable 73
QtyAvailableForStore 73
VersionSync 3041
AverageSaleQty 327
CommentWhenAvailableForStore 88


In [ ]:
idx_bulto = stock[stock['Item'].str.contains('BULTO', na=False)].index
idx_caja = stock[stock['Item'].str.contains('CAJA', na=False)].index

stock.insert(3, 'CAJA_onehot', [1 if i in idx_caja else 0 for i in stock.index])
stock.insert(4, 'BULTO_onehot', [1 if i in idx_bulto else 0 for i in stock.index])

stock.drop(['Package'], axis=1, inplace=True)

stock.head(3)

StockID     Familly                                          Item  \
0        1  DE LA ROSA  de la rosa bianchi choco amarillo 50pz 350gr   
1        2  DE LA ROSA   CAJA de la rosa bianchi choco amarillo c/20   
2        3  DE LA ROSA                de la rosa wafertin 24pz 528gr   

   CAJA_onehot  BULTO_onehot  CostPrice  QtyMinimum  BarCode  PriceList  \
0            0             0       47.4           1       17       60.0   
1            1             0      948.0           0       24     1185.0   
2            0             0       51.4           1       31       65.0   

   QtyAvailable  QtyAvailableForStore  VersionSync  AverageSaleQty  \
0             2                     7       168663           876.0   
1             0                     0       171420             0.0   
2             1                     1       169278            89.0   

    CommentWhenAvailableForStore  
0      2 disponible de inmediato  
1  NO DISPONIBLE (NO PROGRAMADO)  
2      1 disponible de inmediato

In [ ]:
# x = stock[stock['Package']== True]

# # check if item contains "CAJA"
# result = x[x['Item'].str.contains("CAJA", na=False)]

# idx = result.index
# x[~x.index.isin(idx)]

## Preprocesamiento

Los 10 más vendidos

In [ ]:
n_ventas = pd.value_counts(invoicesItems['StockID'].values, sort=True)

n_ventas = pd.DataFrame(n_ventas, columns=['no_ventas'])
n_ventas

no_ventas
66         1009
68          660
1187        645
79          631
118         455
...         ...
1887          1
1706          1
3007          1
2341          1
525           1

[2079 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
n_ventas_max = scaler.fit_transform(n_ventas)

In [ ]:
staff.to_csv('./TablasCleaned/baStaff_cleaned.csv', index=False)
invoices.to_csv('./TablasCleaned/baInvoices_cleaned.csv', index=False)
stock.to_csv('./TablasCleaned/baStock_cleaned.csv', index=False)
invoicesItems.to_csv('./TablasCleaned/baInvoicesItems_cleaned.csv', index=False)